# Generated by Django 3.2.7 on 2021-09-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swheros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='items_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
